/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assi2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JATHURSHAN
 */
public class Table1JFrame extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement p = null;
    ResultSet rs = null;
    String sql;
    
    /**
     * Creates new form NewJFrame
     */
    public Table1JFrame() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Table2Btn = new javax.swing.JButton();
        jLabelTable1 = new javax.swing.JLabel();
        jLabelDname = new javax.swing.JLabel();
        jLabelDnumber = new javax.swing.JLabel();
        jLabelMgr_ssn = new javax.swing.JLabel();
        jLabelMgr_start_date = new javax.swing.JLabel();
        jTextFieldDname = new javax.swing.JTextField();
        jTextFieldDnumber = new javax.swing.JTextField();
        jTextFieldMgr_ssn = new javax.swing.JTextField();
        jTextFieldMgr_start_date = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table2Btn.setText("Table 2");
        Table2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table2BtnActionPerformed(evt);
            }
        });

        jLabelTable1.setText("Table 1");

        jLabelDname.setText("Dname");

        jLabelDnumber.setText("Dnumber");

        jLabelMgr_ssn.setText("Mgr_ssn");

        jLabelMgr_start_date.setText("Mgr_start_date");

        jTextFieldMgr_start_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMgr_start_dateActionPerformed(evt);
            }
        });

        jButtonInsert.setText("Insert");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dname", "Dnumber", "Mgr_ssn", "Mgr_start_date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonSearch.setText("Search by Dnumber");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMgr_start_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMgr_ssn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldDname)
                                            .addComponent(jTextFieldDnumber)
                                            .addComponent(jTextFieldMgr_ssn)
                                            .addComponent(jTextFieldMgr_start_date, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                        .addGap(50, 50, 50))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Table2Btn))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Table2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMgr_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMgr_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMgr_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMgr_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table2BtnActionPerformed
        // TODO add your handling code here:
        // open Table2JFrame
        Table2JFrame jf = new Table2JFrame();
        jf.show();  // display Table2 JFrame
        
        dispose();  // close current JFrame
    }//GEN-LAST:event_Table2BtnActionPerformed

    private void jTextFieldMgr_start_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMgr_start_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMgr_start_dateActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String Dname = jTextFieldDname.getText();
        String Dnumber = jTextFieldDnumber.getText();
        String Mgr_ssn = jTextFieldMgr_ssn.getText();
        String Mgr_start_date = jTextFieldMgr_start_date.getText();
        
        if(Dname.equals("") || Dnumber.equals("") || Mgr_ssn.equals("") || Mgr_start_date.equals("")){
            JOptionPane.showMessageDialog(null, "Fields cannot be null","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            con = DBconnection();
            //clear data on table
            jTable1.setModel(new DefaultTableModel(null, new String[]{"Dname","Dnumber","Mgr_ssn","Mgr_start_date"}));
            
            try{
                //SQL command
                sql = "UPDATE DEPARTMENT SET Dname = ?, Mgr_ssn = ?, Mgr_start_date = ? WHERE Dnumber = ?";
                p = con.prepareStatement(sql);
                
                p.setString(1, Dname);
                p.setInt(2, Integer.parseInt(Mgr_ssn));
                p.setString(3, Mgr_start_date);
                p.setInt(4, Integer.parseInt(Dnumber));
                
                
                int UpdatedRows = p.executeUpdate();
                if(UpdatedRows > 0){ 
                    JOptionPane.showMessageDialog(null, "Update successfull","success",JOptionPane.INFORMATION_MESSAGE);
                    showTableData();
                    //clearing the text fields after updating
                    jTextFieldDname.setText("");
                    jTextFieldDnumber.setText("");
                    jTextFieldMgr_ssn.setText("");
                    jTextFieldMgr_start_date.setText("");
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e,"Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        // Get the data from text fiels
        String Dname = jTextFieldDname.getText();
        String Dnumber = jTextFieldDnumber.getText();
        String Mgr_ssn = jTextFieldMgr_ssn.getText();
        String Mgr_start_date = jTextFieldMgr_start_date.getText();
        
        //check whether the text fields are empty or not
        if(Dname.equals("") || Dnumber.equals("") || Mgr_ssn.equals("") || Mgr_start_date.equals("")){
            JOptionPane.showMessageDialog(null, "Fields cannot be null","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Database connection
            con = DBconnection();
            //clear data on table
            jTable1.setModel(new DefaultTableModel(null, new String[]{"Dname","Dnumber","Mgr_ssn","Mgr_start_date"}));
            
            try{
                //SQL command
                sql = "INSERT INTO DEPARTMENT (Dname,Dnumber,Mgr_ssn,Mgr_start_date) VALUES ('"
                        + Dname + "'," + Integer.parseInt(Dnumber) + "," + Integer.parseInt(Mgr_ssn) + ",'"
                        + Mgr_start_date + "')";
                p = con.prepareStatement(sql);
                
                int insertedRows = p.executeUpdate();
                if(insertedRows > 0){ 
                    JOptionPane.showMessageDialog(null, "Insertion successfull","success",JOptionPane.INFORMATION_MESSAGE);
                    showTableData();
                    //clearing the text fields after inserting
                    jTextFieldDname.setText("");
                    jTextFieldDnumber.setText("");
                    jTextFieldMgr_ssn.setText("");
                    jTextFieldMgr_start_date.setText("");
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e,"Error",JOptionPane.ERROR_MESSAGE);
            }
           
        }
        
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        //check whether the text field is empty or not
        String Dnumber = jTextFieldDnumber.getText();
        
        if(Dnumber.equals("")){
            JOptionPane.showMessageDialog(null, "Dnumber required","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            con = DBconnection();
            //clear data on table
            jTable1.setModel(new DefaultTableModel(null, new String[]{"Dname","Dnumber","Mgr_ssn","Mgr_start_date"}));
            
            try{
                //SQL command
                sql = "DELETE FROM DEPARTMENT WHERE Dnumber = ?";
                p = con.prepareStatement(sql);
                p.setInt(1,Integer.parseInt(Dnumber));
                
                int deletedRows = p.executeUpdate();
                if(deletedRows > 0){ 
                    JOptionPane.showMessageDialog(null, "Deletion successfull","success",JOptionPane.INFORMATION_MESSAGE);
                    showTableData();
                    //clearing the text fields after inserting
                    jTextFieldDnumber.setText("");
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e,"Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
       
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String Dnumber = jTextFieldDnumber.getText();
        //check whether the text field is empty or not
        if(Dnumber.equals("")){
            JOptionPane.showMessageDialog(null, "Dnumber required to search the data",
                    "Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            con = DBconnection();
            
            try{
                //SQL command
                sql = "SELECT *FROM DEPARTMENT WHERE Dnumber = ?";
                p = con.prepareStatement(sql);
                p.setString(1,Dnumber);
                rs = p.executeQuery();
                
                String Dname = "";  // To check a mismatching Dnumber
                while(rs.next()){
                    // get data from the result object
                    Dname = rs.getString("Dname");
                    String Mgr_ssn = rs.getString("Mgr_ssn");
                    String Mgr_start_date = rs.getString("Mgr_start_date");
                    
                    // then set the data to appropriate text fields
                    jTextFieldDname.setText(Dname);
                    jTextFieldMgr_ssn.setText(Mgr_ssn);
                    jTextFieldMgr_start_date.setText(Mgr_start_date);
                }
                
                // if no matching data found 
                //- clear textfields and show error msg
                if("".equals(Dname)){
                    jTextFieldDname.setText("");
                    jTextFieldMgr_ssn.setText("");
                    jTextFieldMgr_start_date.setText("");
                    
                    JOptionPane.showMessageDialog(null, "No data found","Error",
                            JOptionPane.ERROR_MESSAGE);
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e,"Error",JOptionPane.ERROR_MESSAGE);
            }
           
        }
        
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    
    // For Database connection - using JDBC driver (included in the dependencies)
    private Connection DBconnection(){
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root", "");
            
            if(con != null){
                System.out.println("Connected to DB successfully");
                return con;
            }
            else{
                System.out.println("Not Connected to DB");
                return null;
            }
           
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "SQL connection error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    public void showTableData(){
        
        con = DBconnection();
        try{
            sql = "SELECT *FROM DEPARTMENT";
            p = con.prepareStatement(sql);
            rs = p.executeQuery();
           
            while(rs.next()){
                String Dname = rs.getString("Dname");
                String Dnumber = String.valueOf(rs.getInt("Dnumber"));
                String Mgr_ssn = String.valueOf(rs.getInt("Mgr_ssn"));
                String Mgr_start_date = rs.getString("Mgr_start_date");
                
                String data[] = {Dname,Dnumber,Mgr_ssn,Mgr_start_date};
                DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
                tableModel.addRow(data);
            }
            
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table1JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table1JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table1JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table1JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table1JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Table2Btn;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelDname;
    private javax.swing.JLabel jLabelDnumber;
    private javax.swing.JLabel jLabelMgr_ssn;
    private javax.swing.JLabel jLabelMgr_start_date;
    private javax.swing.JLabel jLabelTable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDname;
    private javax.swing.JTextField jTextFieldDnumber;
    private javax.swing.JTextField jTextFieldMgr_ssn;
    private javax.swing.JTextField jTextFieldMgr_start_date;
    // End of variables declaration//GEN-END:variables
}
